### ISSUE TITLE
Padding vs breakpoints

### ISSUE THREAD

**Issue by TidyCustoms** [lgse/micro-slider#2]
Hello, 
Thank you for the great script. I have a plan to use it on my new, upcoming website.
I can not find an answer how to chnage the padding variable  depending on brakpoints?
I would like to have for example: for 1200px viewport padding variables: 900, but for 2500px - 1800

```
<script type="text/javascript">
        window.onload = function() {
            new MicroSlider('.micro-slider', {
                indicators: false,
                perspectiveFactor: 1.15,
                zoomScale: -475,
                padding: 1800,
               transitionDuration: 150,
            });
        }
</script>
```

**Comment by l0gicgate** [comment]
So what you can do instead is to pad the container containing the micro slider and put your breakpoints on that element instead.
